name: 'List Pull Requests'
description: 'list and put output pull requests'
branding:
  icon: 'bell'  
  color: 'yellow'
inputs:
  token:
    description: 'github token'
    required: true
    default: ''
  labels:
    description: 'require labels to list (JSON array string)'
    required: false
    default: '[ "WFR" ]'
outputs:
  result:
    description: 'pull request string'
runs:
  using: 'node12'
  main: 'dist/index.js'
